# Node docker image on which this would be run
image: node:8.9.0

#This command is run before actual stages start running
before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - npm install

stages:
  - deploy

# lint and test are two different jobs in the same stage.
# This allows us to run these two in parallel and making build faster

# Job 1:
#lint:
#  stage: test
#  script:
#    - npm run lint

# Job 2:
#test:
#  stage: test
#  script:
#    - chmod +x node_modules/.bin/react-scripts
#    - npm run test

deployToAWS:
  only:
    - master
  stage: deploy
  script:
    - chmod +x ./deploy/deploy.sh
    - chmod +x ./deploy/disableHostKeyChecking.sh
    - chmod +x ./deploy/updateAndRestart.sh
    - bash deploy/deploy.sh